/** Frozen pre-integration driver, used only to reproduce the saved proposal. */
export const legacyRunJump = [
  "function runJump({ onFlash, onDone, lead = 0 }) {",
  "  /* The driver. Measures the world at the press, hands the drawing to",
  "     arrivalEngineCore , inside a Worker with an OffscreenCanvas wherever the",
  "     browser has one, so the tunnel keeps its frame rate while the main thread",
  "     mounts the dashboard , and keeps for itself the two jobs a worker cannot",
  "     do: choreographing the DOM (the card's fade, the clouds' pull and blow-out)",
  "     and the flash handover. */",
  "  const root = typeof document === \"undefined\" ? null : document.documentElement;",
  "  if (!root) { onFlash(); onDone(); return () => {}; }",
  "  // A repeat or reduced-motion sign-in owns a new handoff too. Never inherit",
  "  // the previous session's landed latch and expose the app before this one ends.",
  "  jumpOwnsEntrance = true;",
  "  jumpLanded = false;",
  "  jumpShort = arrivalShort();",
  "  if (jumpShort) {",
  "    tellPhase(\"cruise\");",
  "    const t = setTimeout(() => { onFlash(); onDone(); }, 180);",
  "    return () => { clearTimeout(t); jumpOwnsEntrance = false; tellPhase(\"off\"); };",
  "  }",
  "",
  "  const W = window.innerWidth, H = window.innerHeight;",
  "  const cx = W / 2, cy = H / 2;",
  "  lastJumpOrigin = { x: cx, y: cy };",
  "  root.style.setProperty(\"--jx\", cx + \"px\");",
  "  root.style.setProperty(\"--jy\", cy + \"px\");",
  "",
  "  /* ---- the mark, measured where it actually sits ---- */",
  "  const gWord = sageDots({ word: true });",
  "  let mk = [];",
  "  if (lastMarkEl) {",
  "    const mr = lastMarkEl.getBoundingClientRect();",
  "    const scale = Math.min(mr.width / gWord.w, mr.height / gWord.h) || 1;",
  "    const ox = mr.left + (mr.width - gWord.w * scale) / 2;",
  "    const oy = mr.top + (mr.height - gWord.h * scale) / 2;",
  "    const gS = sageDots({ word: false });",
  "    const seatScale = scale * 0.62;",
  "    const seats = gS.dots.map((d) => ({",
  "      x: cx + (d.x - gS.w / 2) * seatScale,",
  "      y: cy + (d.y - gS.h / 2) * seatScale,",
  "      r: d.r * seatScale,",
  "    })).sort((a, b) => a.x - b.x || a.y - b.y);",
  "    const home = gWord.dots.map((d) => ({ x: ox + d.x * scale, y: oy + d.y * scale, r: d.r * scale, fill: d.fill }))",
  "      .sort((a, b) => a.x - b.x || a.y - b.y);",
  "    const spanX = (home[home.length - 1].x - home[0].x) || 1;",
  "    mk = home.map((d, i) => {",
  "      const seat = seats[Math.round((i * (seats.length - 1)) / (home.length - 1))] || { x: cx, y: cy, r: d.r };",
  "      return { hx: d.x, hy: d.y, hr: d.r, fill: d.fill,",
  "        sx: seat.x, sy: seat.y, sr: seat.r,",
  "        delay: (d.x - home[0].x) / spanX, jit: Math.random() };",
  "    });",
  "  }",
  "",
  "  /* ---- the field: the page's own grid, continued past every edge ---- */",
  "  const field = [];",
  "  {",
  "    let i = 0;",
  "    for (let y = GROUND_PITCH / 2; y < H; y += GROUND_PITCH)",
  "      for (let x = GROUND_PITCH / 2; x < W; x += GROUND_PITCH) {",
  "        const bright = i % 3 === 0;",
  "        field.push({ x, y, size: bright ? 4.4 : 2.6, tint: GROUND_TINTS[i % GROUND_TINTS.length], jit: Math.random() });",
  "        i++;",
  "      }",
  "    const padX = W * 0.5, padY = H * 0.5;",
  "    for (let y = GROUND_PITCH / 2 - padY; y < H + padY; y += GROUND_PITCH)",
  "      for (let x = GROUND_PITCH / 2 - padX; x < W + padX; x += GROUND_PITCH) {",
  "        if (x > 0 && x < W && y > 0 && y < H) continue;",
  "        const bright = i % 3 === 0;",
  "        field.push({ x, y, size: bright ? 4.4 : 2.6, tint: GROUND_TINTS[i % GROUND_TINTS.length], jit: Math.random() });",
  "        i++;",
  "      }",
  "  }",
  "",
  "  /* ---- the tunnel: seeded mid-life so the sky starts in steady state ---- */",
  "  const maxR = Math.hypot(W, H) / 2 + 160;",
  "  const tunnel = [];",
  "  {",
  "    const n = Math.round((W * H) / 7800);",
  "    for (let i = 0; i < n; i++) {",
  "      const waiting = Math.random() < 0.18;",
  "      const r = waiting ? 2 : Math.pow(Math.random(), 1.7) * maxR;",
  "      tunnel.push({",
  "        ang: Math.random() * Math.PI * 2, r,",
  "        t: Math.max(0, r - (200 + Math.random() * 160)),",
  "        wait: waiting ? Math.random() * 0.9 : 0,",
  "        v: 0.55 + Math.random() * 0.9,",
  "        size: 1.4 + Math.random() * 2.2,",
  "        tint: GROUND_TINTS[Math.floor(Math.random() * GROUND_TINTS.length)],",
  "      });",
  "    }",
  "  }",
  "",
  "  const cv = document.createElement(\"canvas\");",
  "  cv.className = \"sage-jump-canvas\";",
  "  const dpr = Math.min(2, window.devicePixelRatio || 1);",
  "  cv.width = Math.round(W * dpr); cv.height = Math.round(H * dpr);",
  "  cv.style.width = W + \"px\"; cv.style.height = H + \"px\";",
  "  document.body.appendChild(cv);",
  "  root.classList.add(\"sage-cv\");",
  "",
  "  const card = document.querySelector(\".login-card\");",
  "  const blobs = Array.from(document.querySelectorAll(\".sg-blob\")).map((el) => {",
  "    const r = el.getBoundingClientRect();",
  "    const bx = r.left + r.width / 2, by = r.top + r.height / 2;",
  "    const dx = bx - cx, dy = by - cy, dist = Math.hypot(dx, dy) || 1;",
  "    return { el, ux: dx / dist, uy: dy / dist };",
  "  });",
  "  const restoreDom = () => {",
  "    if (card) { card.style.opacity = \"\"; card.style.transform = \"\"; }",
  "    for (const b of blobs) { b.el.style.transform = \"\"; b.el.style.opacity = \"\"; }",
  "  };",
  "  const bodyFont = (() => {",
  "    try { return getComputedStyle(document.body).fontFamily || \"sans-serif\"; }",
  "    catch (e) { return \"sans-serif\"; }",
  "  })();",
  "",
  "  const world = { W, H, dpr, T: JUMP_T, FP: 0.5, mk, field, tunnel, font: bodyFont, lead };",
  "",
  "  let flashing = false, stopped = false, raf = 0, domRaf = 0;",
  "  let worker = null, engine = null, cancelCover = () => {};",
  "",
  "  const toFlash = () => {",
  "    if (flashing || stopped) return;",
  "    flashing = true;",
  "    activeEngineSend = null;",
  "    root.classList.add(\"sage-beat-flash\", \"sage-cover-active\");",
  "    if (worker) { try { worker.terminate(); } catch (e) {} worker = null; }",
  "    onFlash();",
  "    cancelCover = waitForArrivalCover(() => {",
  "      if (stopped) return;",
  "      restoreDom();",
  "      root.classList.remove(\"sage-cv\");",
  "      if (cv.parentNode) cv.parentNode.removeChild(cv);",
  "      onDone();",
  "    });",
  "  };",
  "",
  "  const onPost = (type, data) => {",
  "    if (stopped) return;",
  "    if (type === \"phase\") tellPhase(data);",
  "    else if (type === \"flash\") toFlash();",
  "  };",
  "",
  "  /* Worker where the browser has one; the same core on the main thread where",
  "     it does not. Either way the maths exists once. */",
  "  let usingWorker = false;",
  "  try {",
  "    if (typeof OffscreenCanvas !== \"undefined\" && cv.transferControlToOffscreen && typeof Worker !== \"undefined\") {",
  "      const off = cv.transferControlToOffscreen();",
  "      const src = \"let eng=null;self.onmessage=function(e){var m=e.data;\" +",
  "        \"if(m.type==='init'){var ctx=m.canvas.getContext('2d');\" +",
  "        \"var core=(\" + arrivalEngineCore.toString() + \");\" +",
  "        \"eng=core(ctx,m.world,function(t,d){self.postMessage({type:t,data:d});});\" +",
  "        \"var loop=function(now){if(!eng)return;eng.tick(now);requestAnimationFrame(loop);};\" +",
  "        \"requestAnimationFrame(loop);}else if(eng){eng.msg(m);}};\";",
  "      worker = new Worker(URL.createObjectURL(new Blob([src], { type: \"text/javascript\" })));",
  "      worker.onmessage = (e) => onPost(e.data.type, e.data.data);",
  "      worker.postMessage({ type: \"init\", canvas: off, world }, [off]);",
  "      usingWorker = true;",
  "    }",
  "  } catch (e) { try { if (worker) worker.terminate(); } catch (e2) {} worker = null; usingWorker = false; }",
  "  if (!usingWorker) {",
  "    const ctx = cv.getContext(\"2d\");",
  "    engine = arrivalEngineCore(ctx, world, onPost);",
  "    const loop = (now) => {",
  "      if (stopped || flashing) return;",
  "      engine.tick(now);",
  "      raf = requestAnimationFrame(loop);",
  "    };",
  "    raf = requestAnimationFrame(loop);",
  "  }",
  "  activeEngineSend = (m) => {",
  "    if (worker) worker.postMessage(m);",
  "    else if (engine) engine.msg(m);",
  "  };",
  "  activeEngineSend({ type: \"ready\", ready: arrivalReady });",
  "  activeEngineSend({ type: \"dest\", dest: arrivalDest });",
  "",
  "  /* ---- the DOM's own choreography, on a matching clock ----",
  "     The card's fade and the clouds' pull and blow-out are DOM work, which a",
  "     worker cannot touch. They run here, done before the cruise begins , which",
  "     is exactly why the dashboard mount was moved INTO the cruise: by then the",
  "     main thread has nothing visual left to animate. */",
  "  const ease3 = (p) => 1 - Math.pow(1 - Math.min(1, Math.max(0, p)), 3);",
  "  const pw = (p, k) => Math.pow(Math.min(1, Math.max(0, p)), k);",
  "  const domT0 = performance.now() + lead;",
  "  const R = JUMP_T.ratchet, F = JUMP_T.reform, S = JUMP_T.streaks;",
  "  const domLoop = (now) => {",
  "    if (stopped || flashing) return;",
  "    const t = now - domT0;",
  "    if (t >= R && t < R + F) {",
  "      const k = ease3((t - R) / F);",
  "      if (card) {",
  "        card.style.opacity = String(Math.max(0, 1 - k * 1.15));",
  "        card.style.transform = \"scale(\" + (1 - k * 0.08) + \")\";",
  "      }",
  "      for (const b of blobs) {",
  "        b.el.style.transform = \"translate(\" + (-b.ux * k * 150) + \"px,\" + (-b.uy * k * 150) + \"px) scale(\" + (1 - k * 0.1) + \")\";",
  "        b.el.style.opacity = String(1 - k * 0.3);",
  "      }",
  "    } else if (t >= R + F && t < R + F + S) {",
  "      const k = pw((t - R - F) / S, 1.8);",
  "      const out = k * Math.max(W, H) * 0.75;",
  "      if (card) card.style.opacity = \"0\";",
  "      for (const b of blobs) {",
  "        b.el.style.transform = \"translate(\" + (b.ux * (out - 150 * (1 - k))) + \"px,\" + (b.uy * (out - 150 * (1 - k))) + \"px) scale(\" + (0.9 + k * 0.5) + \")\";",
  "        b.el.style.opacity = String(Math.max(0, 0.7 - k * 1.1));",
  "      }",
  "    } else if (t >= R + F + S) {",
  "      if (card) card.style.opacity = \"0\";",
  "      for (const b of blobs) b.el.style.opacity = \"0\";",
  "      return;   // nothing left for the main thread to animate",
  "    }",
  "    domRaf = requestAnimationFrame(domLoop);",
  "  };",
  "  domRaf = requestAnimationFrame(domLoop);",
  "",
  "  return () => {",
  "    stopped = true;",
  "    cancelCover();",
  "    activeEngineSend = null;",
  "    cancelAnimationFrame(raf); cancelAnimationFrame(domRaf);",
  "    if (worker) { try { worker.postMessage({ type: \"stop\" }); worker.terminate(); } catch (e) {} worker = null; }",
  "    if (engine) engine.msg({ type: \"stop\" });",
  "    restoreDom();",
  "    root.classList.remove(\"sage-cv\", \"sage-beat-flash\", \"sage-cover-active\");",
  "    if (cv.parentNode) cv.parentNode.removeChild(cv);",
  "    jumpOwnsEntrance = false;",
  "    tellPhase(\"off\");   // release the mount gate: this jump is not landing",
  "  };",
  "}",
  "",
].join("\n");
